version: 2

models:
    - name: dl_customer_consume
      description: "Testing Incremental Updates"
      columns:
          - name: custkey
            description: "The primary key for this table"
            tests:
                - unique
                - not_null